"""rename fields

Revision ID: 766e69e9a76d
Revises: 93bec5ba79d0
Create Date: 2024-11-16 17:33:12.737239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766e69e9a76d'
down_revision = '93bec5ba79d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rma_status_association', sa.Column('user_status_association_id', sa.Integer(), nullable=False))
    op.drop_constraint('rma_status_association_status_id_fkey', 'rma_status_association', type_='foreignkey')
    op.create_foreign_key(None, 'rma_status_association', 'user_status_association', ['user_status_association_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rma_status_association', 'status_id')
    op.add_column('user_status_association', sa.Column('status', sa.String(length=255), nullable=False))
    op.drop_column('user_status_association', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_status_association', sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('user_status_association', 'status')
    op.add_column('rma_status_association', sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'rma_status_association', type_='foreignkey')
    op.create_foreign_key('rma_status_association_status_id_fkey', 'rma_status_association', 'user_status_association', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_column('rma_status_association', 'user_status_association_id')
    # ### end Alembic commands ###
