"""create statuses for rma

Revision ID: 3f7b9407b49e
Revises: bf1633691e61
Create Date: 2024-11-13 06:41:15.562141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7b9407b49e'
down_revision = 'bf1633691e61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rma_status_association',
    sa.Column('rma_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rma_id'], ['rmas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rma_id', 'status_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rma_status_association')
    op.drop_table('status')
    # ### end Alembic commands ###
