"""add color and model

Revision ID: b8f5002784bb
Revises: 8b7a765bac81
Create Date: 2024-11-13 23:35:03.106789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8f5002784bb'
down_revision = '8b7a765bac81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rmas', sa.Column('model', sa.String(length=255), nullable=False))
    op.add_column('rmas', sa.Column('color', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rmas', 'color')
    op.drop_column('rmas', 'model')
    # ### end Alembic commands ###
