"""add user_id into status table

Revision ID: e15444e51a8a
Revises: 3f7b9407b49e
Create Date: 2024-11-13 08:29:12.895628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15444e51a8a'
down_revision = '3f7b9407b49e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key("user_id_fk", 'status', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_id_fk", 'status', type_='foreignkey')
    op.drop_column('status', 'user_id')
    # ### end Alembic commands ###
