"""rename table

Revision ID: 93bec5ba79d0
Revises: 594d17cf65e1
Create Date: 2024-11-16 17:26:55.079628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '93bec5ba79d0'
down_revision = '594d17cf65e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rma_status_association_status_id_fkey', 'rma_status_association', type_='foreignkey')
    op.create_table('user_status_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('status')
    op.create_foreign_key(None, 'rma_status_association', 'user_status_association', ['status_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('rma_status_association_status_id_fkey', 'rma_status_association', 'status', ['status_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'rma_status_association', type_='foreignkey')
    op.create_table('status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_id_fk', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='status_pkey')
    )
    op.drop_table('user_status_association')
    # ### end Alembic commands ###
