"""add creatd_at field

Revision ID: 8b7a765bac81
Revises: c3f48435240d
Create Date: 2024-11-13 10:18:41.873273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b7a765bac81'
down_revision = 'c3f48435240d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rmas', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('status', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'created_at')
    op.drop_column('rmas', 'created_at')
    # ### end Alembic commands ###
