"""drop rma user association table

Revision ID: c3f48435240d
Revises: e15444e51a8a
Create Date: 2024-11-13 08:51:35.595481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f48435240d'
down_revision = 'e15444e51a8a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rma_user_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rma_user_association',
    sa.Column('rma_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rma_id'], ['rmas.id'], name='rma_user_association_rma_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='rma_user_association_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rma_id', 'user_id', name='rma_user_association_pkey')
    )
    # ### end Alembic commands ###
