"""drop reason field

Revision ID: 594d17cf65e1
Revises: b8f5002784bb
Create Date: 2024-11-13 23:39:11.476133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594d17cf65e1'
down_revision = 'b8f5002784bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
